const adminEmails = ["yakububilyaminu44@gmail.com","abalhafsa@gmail.com","kabironifade@gmail.com","msanusi2009@yahoo.co.uk"];
let users = []; let currentUser = null;
document.getElementById('toSignup').addEventListener('click', e=>{e.preventDefault(); document.getElementById('login-box').classList.add('hidden'); document.getElementById('signup-box').classList.remove('hidden');});
document.getElementById('toLogin').addEventListener('click', e=>{e.preventDefault(); document.getElementById('signup-box').classList.add('hidden'); document.getElementById('login-box').classList.remove('hidden');});
document.getElementById('registerBtn').addEventListener('click', ()=>{ const name=document.getElementById('name').value.trim(); const fileNo=document.getElementById('fileNo').value.trim(); const ippis=document.getElementById('ippis').value.trim(); const dept=document.getElementById('dept').value.trim(); const phone=document.getElementById('phone').value.trim(); const email=document.getElementById('email').value.trim(); if(!name||!fileNo||!ippis||!dept||!phone||!email){ document.getElementById('regMsg').textContent='Please fill all fields.'; return; } const id=String(users.length+1).padStart(4,'0'); users.push({id,name,fileNo,ippis,dept,phone,email,approved:false,balance:0,loan:0,monthlyDeduction:0}); document.getElementById('regMsg').textContent='Registered. Await admin approval. Your ID: '+id; ['name','fileNo','ippis','dept','phone','email'].forEach(i=>document.getElementById(i).value=''); });
document.getElementById('loginBtn').addEventListener('click', ()=>{ const uid=document.getElementById('uid').value.trim(); const user=users.find(u=>u.id===uid && u.approved); if(!user){ document.getElementById('loginMsg').textContent='Invalid or unapproved ID'; return;} currentUser=user; showDashboard(); });
function showDashboard(){ document.getElementById('auth').classList.add('hidden'); document.getElementById('dashboard').classList.remove('hidden'); document.getElementById('memberName').textContent=currentUser.name; document.getElementById('savings').textContent='₦'+(currentUser.balance||0).toLocaleString(); document.getElementById('loan').textContent='₦'+(currentUser.loan||0).toLocaleString(); document.getElementById('deduct').textContent='₦'+(currentUser.monthlyDeduction||0).toLocaleString(); }
document.getElementById('logoutBtn').addEventListener('click', ()=>{ currentUser=null; document.getElementById('dashboard').classList.add('hidden'); document.getElementById('auth').classList.remove('hidden'); document.getElementById('loginMsg').textContent='Logged out';});
document.getElementById('viewItemsBtn').addEventListener('click', ()=>{ document.getElementById('contentArea').innerHTML='<h3>Commodities posted by admin</h3><ul><li>Rice - ₦15,000</li><li>Sugar - ₦8,000</li></ul>'; });
document.getElementById('applyLoanBtn').addEventListener('click', ()=>{ const form=`<h3>Apply for Loan</h3><select id="loanType"><option>Business Loan</option><option>Short-Term Loan</option><option>Long-Term Loan</option></select><input id="loanAmount" placeholder="Amount" type="number"><button id="submitLoan">Submit</button>`; document.getElementById('contentArea').innerHTML=form; document.getElementById('submitLoan').addEventListener('click', ()=>{ const amt=Number(document.getElementById('loanAmount').value); const type=document.getElementById('loanType').value; if(!amt||amt<=0){ alert('Enter valid amount'); return;} if(currentUser){ currentUser.pendingLoan={amount:amt,type,status:'pending'}; alert('Loan request submitted (pending approval)'); document.getElementById('contentArea').innerHTML=''; } }); });
window._demo={users:users,approveUser:function(id){const u=users.find(x=>x.id===id); if(u){u.approved=true; return true;} return false;},approveLoan:function(id){const u=users.find(x=>x.id===id); if(u&&u.pendingLoan){u.loan=u.pendingLoan.amount;u.pendingLoan.status='approved';return true;}return false;}};
